// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXYvw2V4Pc5yHY-9fwtdUyRqrOlgzxio',
    appId: '1:594325238623:web:b595a6e4996278263f7cea',
    messagingSenderId: '594325238623',
    projectId: 'chat-app-a1664',
    authDomain: 'chat-app-a1664.firebaseapp.com',
    storageBucket: 'chat-app-a1664.firebasestorage.app',
    measurementId: 'G-WF72WHWSDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJuiSsvNz2rOD8RrfW1zwl-Vp4oO9xDE',
    appId: '1:594325238623:android:c3aeed2110d7ab833f7cea',
    messagingSenderId: '594325238623',
    projectId: 'chat-app-a1664',
    storageBucket: 'chat-app-a1664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrCLXM7pxmoEyun-0sGyDPxAuA-2XJVQ',
    appId: '1:594325238623:ios:82e2b8c5cb9617ea3f7cea',
    messagingSenderId: '594325238623',
    projectId: 'chat-app-a1664',
    storageBucket: 'chat-app-a1664.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhrCLXM7pxmoEyun-0sGyDPxAuA-2XJVQ',
    appId: '1:594325238623:ios:82e2b8c5cb9617ea3f7cea',
    messagingSenderId: '594325238623',
    projectId: 'chat-app-a1664',
    storageBucket: 'chat-app-a1664.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoXYvw2V4Pc5yHY-9fwtdUyRqrOlgzxio',
    appId: '1:594325238623:web:9dc23f23c7efab693f7cea',
    messagingSenderId: '594325238623',
    projectId: 'chat-app-a1664',
    authDomain: 'chat-app-a1664.firebaseapp.com',
    storageBucket: 'chat-app-a1664.firebasestorage.app',
    measurementId: 'G-2FJ9213V2X',
  );
}
